- spec/models/task_spec.rb
- spec/models/tracking_spec.rb
- spec/models/user_spec.rb
@jensendarren 
Refactor code on #describe scope in model spec task.
Please check it
> fix model spec task

- spec/models/assessment_domain_spec.rb
- spec/models/assessment_spec.rb
- spec/models/case_note_domain_group_spec.rb
- spec/models/case_note_spec.rb
- spec/models/case_spec.rb
- spec/models/changelog_spec.rb
- spec/models/client_enrollment_history_spec.rb
- spec/models/client_enrollment_spec.rb
- spec/models/client_enrollment_tracking_spec.rb
- spec/models/client_spec.rb
- spec/models/custom_field_spec.rb
- spec/models/enter_ngo_spec.rb
- spec/models/exit_ngo_spec.rb
- spec/models/organization_spec.rb
- spec/models/program_stream_spec.rb
- spec/models/referral_spec.rb
- spec/models/setting_spec.rb
- spec/models/visit_spec.rb
@jensendarren 
Fix model referral spec.
Please check it.
> fix model referral spec

- app/controllers/calls_controller.rb
- app/javascript/components/Commons/ListTable/index.js
- app/javascript/components/DetailCall/_call.js
- app/javascript/components/DetailCall/_list-client.js
- app/javascript/components/DetailCall/_referee.js
- app/javascript/components/DetailCall/helper.js
- app/javascript/components/DetailCall/index.js
- app/views/calls/show.haml
- app/views/clients/show.haml
@sophalsun, @PirunSeng 
Please Kindly Check.
> Hotline call detail

- app/controllers/clients_controller.rb
As observe the code, this issue should also appear on production just that no one try to do it yet.
https://appsignal.com/rotati/sites/5943867022139345e7ef3fa1/exceptions/incidents/692
> Fix destroying client

- app/javascript/components/NewClientForm/referralInfo.js
https://trello.com/c/XtoSiY8f/9-client-birth-province-field-disappeared-on-the-add-new-client-form-week-18
> Fixed hidden birth province

- app/assets/javascripts/program_streams/form.coffee
Signed-off-by: kirykr <kirymeas@gmail.com>
> 2020051904 remove program stream tracking paragraph field

- app/controllers/api/v1/organizations_controller.rb
- app/models/client.rb
- app/models/commune.rb
- app/models/district.rb
- app/models/province.rb
- app/models/village.rb
- config/initializers/array.rb
- config/routes.rb
- lib/tasks/import_communes_and_villages.rake
Must import addresses to shared tenant.
> Improve duplicate checker

- app/serializers/client_serializer.rb
@kirykr 
Fix error time in cps and time in ngo
> fix error time in cps and time in ngo

- app/assets/javascripts/client_advance_search.coffee
- app/assets/javascripts/clients/index.coffee
- app/controllers/domains_controller.rb
- app/grids/client_grid.rb
- app/helpers/assessment_helper.rb
- app/models/domain.rb
- app/views/assessments/_form.html.haml
- app/views/assessments/index.html.haml
- app/views/domains/_domain_list.haml
- app/views/domains/_form.html.haml
- config/locales/en.yml
- config/locales/km.yml
- config/locales/my.yml
- db/migrate/20201222115437_add_more_scores_to_domain.rb
- db/schema.rb
> Ai framework custom assessment score 1 to 10

- app/models/assessment.rb
> 2022010211 Do no update assessment complete date if the assessment already completed

- spec/features/assessment_spec.rb
- spec/features/care_plan_spec.rb
- spec/features/case_note_spec.rb
- spec/features/family_spec.rb
- spec/features/login_spec.rb
- spec/features/report_builder_spec.rb
- spec/features/start_page_spec.rb
- spec/features/user_spec.rb
- spec/requests/api/v1/client_duplicate_checker_spec.rb
- spec/requests/api/v1/clients_controller_spec.rb
> [IMP] Add browser test

- config/jenkins/uat/latest.sh
> [IMP] Add script for run test

- spec/features/agency_spec.rb
- spec/features/family_spec.rb
- spec/features/report_builder_spec.rb
> [IMP] Add sleep for test

- config/environments/test.rb
> [IMP] Add cache configuration

- app/models/quantitative_type.rb
- app/models/tracking.rb
- spec/classes/client_advanced_searches/quantitative_case_fields_spec.rb
- spec/classes/dashboard_spec.rb
- spec/features/agency_spec.rb
- spec/features/domain_group_spec.rb
- spec/features/donor_spec.rb
- spec/features/family_spec.rb
- spec/features/organization_type_spec.rb
- spec/features/partner_spec.rb
- spec/features/quantitative_type_spec.rb
- spec/features/report_builder_spec.rb
- spec/features/user_spec.rb
- spec/models/assessment_spec.rb
> [IMP] Update test

- spec/features/report_builder_spec.rb
> [IMP] Update report builder test

- spec/features/family_spec.rb
- spec/features/report_builder_spec.rb
> [IMP] Add clear cache test

- spec/features/family_spec.rb
- spec/features/report_builder_spec.rb
> [IMP] Update search test

- spec/features/family_spec.rb
> [IMP] Improve family test

- app/classes/advanced_searches/client_fields.rb
- app/classes/advanced_searches/csi_fields.rb
- app/classes/advanced_searches/custom_domain_score_fields.rb
- app/classes/advanced_searches/domain_score_fields.rb
- app/helpers/advanced_search_helper.rb
- config/locales/en.yml
- config/locales/km.yml
- config/locales/my.yml
- config/locales/ne.yml
- config/locales/th-TH.yml
> [IMP] Group search criteria

- app/classes/advanced_searches/client_association_filter.rb
- app/classes/advanced_searches/client_fields.rb
- app/helpers/advanced_search_helper.rb
- app/views/clients/client_advanced_searches/_form_option.haml
- config/locales/en.yml
- config/locales/km.yml
- config/locales/my.yml
> [BUGFIX] Fix feedback

- app/views/clients/_table_summary_age_tab.haml
- app/views/clients/_table_summary_referral_category_tab.haml
- app/views/clients/index.html.haml
> [BUGFIX] Fix age & referral categories summary rpt

- app/classes/advanced_searches/client_association_filter.rb
> [BUGFIX] Fix number of billable clients rpt

- app/views/clients/_table_summary_age_tab.haml
- app/views/clients/_table_summary_referral_category_tab.haml
> [IMP] Improve table summary age & referral category

- app/classes/advanced_searches/client_association_filter.rb
> [BUGFIX] Fix number billable client report

- app/views/clients/_table_summary_age_tab.haml
- config/locales/en.yml
- config/locales/km.yml
- config/locales/my.yml
> [IMP] Count age by gender in Age summary tab

- app/controllers/api/clients_controller.rb
> [IMP] Round assessment score up

- app/assets/javascripts/clients/index.coffee
- app/assets/stylesheets/clients/client_grid.scss
- app/views/datagrid/_form.html.haml
> [IMP] Filter client column picker

- app/classes/advanced_searches/client_association_filter.rb
> [IMP] Fix assessment reports comparison

- app/classes/advanced_searches/client_association_filter.rb
> [IMP] Fix Active Client specific period & program

- app/models/client.rb
https://trello.com/c/awdpnmvb/31-cif-click-referral-client-meets-error-500
> Fix Client.get_address_by_code argument

- app/models/client.rb
https://appsignal.com/children-in-families/sites/61a5fe0e7ccda63da7f9a5a0/exceptions/incidents/1387
> Fix bad return from Client.get_client_attribute

- app/controllers/concerns/client_grid_options.rb
- app/grids/client_grid.rb
- config/initializers/datagrid.rb
https://trello.com/c/mYZP1QTb/46-102-data-expanding-assessment
> Expand client report - CSI assessment

- app/assets/stylesheets/clients/show.scss
- app/models/quantitative_type.rb
- app/views/clients/_referral_more_info.haml
- app/views/clients/show.haml
- config/locales/en.yml
- config/locales/km.yml
- config/locales/my.yml
- config/locales/ne.yml
https://trello.com/c/2WRTvpSl/18-63-refactor-client-show-page-ui
> 6.3 Update client show page

- app/assets/stylesheets/clients/show.scss
- app/assets/stylesheets/common_version.scss
- app/helpers/families_helper.rb
- app/views/families/show.html.haml
- app/views/families/show/_about.haml
- config/locales/en.yml
- config/locales/km.yml
https://trello.com/c/7FRAcaW5/19-64-refactor-family-show-page-ui
> update family UI

- app/controllers/assessments_controller.rb
- app/controllers/concerns/assessment_concern.rb
- app/models/assessment.rb
https://[trello.com/1/cards/64b76d7c95e80d96d4bd7b9b/attachments/64b7a3999225b5a1e1733a31/download/Ratanak_Assessment_Error.mp4](https://trello.com/1/cards/64b76d7c95e80d96d4bd7b9b/attachments/64b7a3999225b5a1e1733a31/download/Ratanak_Assessment_Error.mp4)
> Fix passing params

- app/classes/advanced_searches/families/family_base_sql_builder.rb
- app/helpers/form_builder_helper.rb
Fix filter custom field not blank
> Family advance search

- app/classes/advanced_searches/client_association_filter.rb
- app/controllers/api/clients_controller.rb
- app/controllers/family/assessments_controller.rb
Fix loading assessment data into summary table in advance search.
> Fix fetching assessment data

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/javascript/components/NewClientForm/index.js
- app/models/client.rb
- app/views/clients/index.html.haml
- config/environments/demo.rb
- config/environments/production.rb
- config/environments/ratanak_staging.rb
- config/environments/staging.rb
- db/migrate/20240626213339_add_index_to_shared_clients_resolved_duplication_by.rb
- db/migrate/20240626214411_add_index_to_shared_clients_archived_slug.rb
- db/schema.rb
Trello: https://trello.com/c/Y14l880X/137-troubleshooting-slow-request-query-phase-2
This PR contains improvement for:
1. Client report builder page - blank filter
2. Duplicate checker
> Improve page load performance

- app/assets/stylesheets/families/show.scss
- app/controllers/enrolled_programs_controller.rb
- app/controllers/families_controller.rb
- app/models/enrollment.rb
- app/views/custom_field_properties/index.haml
- app/views/enrolled_programs/_manage.haml
- app/views/families/custom_fields.html.haml
- app/views/families/show.html.haml
- app/views/family_referrals/index.haml
- app/views/referrals/index.haml
- config/deploy/staging.rb
- config/locales/en.yml
- config/routes.rb
Trello card: https://trello.com/c/sqBbOEyN/141-ux-ui-improvement-family
> Grouping actions in family show page

- app/mailers/case_worker_mailer.rb
- app/mailers/internal_referral_mailer.rb
- app/mailers/remind_manager_mailer.rb
This debugging is no longer needed.
> Remove debugging bcc
